### ISSUE TITLE
Language changes to German when using load at start

### ISSUE THREAD

**Issue by gavinsbtm** [Securepoint/openvpn-client#10]
Installed the program in English and set the load at start up option. When the program starts up, the language has changed to German.

**Comment by wget** [comment]
@gavinsbtm Hello. I was updating my chocolatey package and tried to check your issue in the process, but cannot reproduce it :-/ 

Could you explain in details what you did (which  ` load at start up option` feature are you talking about?) and specify which exact OS version you have.

In which language is set your OS? What are your regional settings and your keyboard layout.

I sometimes have issues with software when everything is in English except the locale for the regional settings (this might explain the issue).

**Comment by gavinsbtm** [comment]
This seemed to only happen straight after installation. Once Windows had been restarted, the language was correct.

**Comment by wget** [comment]
@gavinsbtm I'm still unable to reproduce on the different VMs I have (Windows 7 and 10, both installed in English).

But you didn't answer my previous questions. In which language was installed your OS? German?

**Comment by gavinsbtm** [comment]
OS Language and keyboard layout are both English UK.

While ago when I installed but pretty sure there was a "Load at start" checkbox during the installation.

**Comment by wget** [comment]
@gavinsbtm If you and I aren't able to reproduce, I propose to close this bug report.
Indeed, there have been some changes recently wrt. the installer, so I assume this problem is likely to be fixed. cf. [old installation process which has changed since](https://github.com/Securepoint/openvpn-client/issues/9#issuecomment-275355160).

**Comment by gavinsbtm** [comment]
No problem. Thanks.

Great piece of software by the way.

**Comment by wget** [comment]
@gavinsbtm I'm not a developer for this piece of software, nor am I able to close any bug report / fix bugs / commit for it :)  [I'm just packaging it for chocolatey as a volunteer](https://chocolatey.org/packages/securepointsslvpn/) :)

**Comment by rmiddle** [comment]
I can confirm the problem with German Lang when you go into Start on windows startup in the client setting windows under 2.0.18.  Have had a change to confirm if it is still happening under 2.0.20 yet.

**Comment by QtOlli** [comment]
Fixed in 2.0.21

**Comment by mrez-ir** [comment]
here I'm using openvpn GUI v 11.10.0.0 and this bug still present.
I tried to hide script windows, make silent connection, disable baloon from settings. but no luck.
Its too annoying and always switch and set keyboard language and direction to default "right to left" (its not only for German) even for a simple reconnect when a network problem occurs while all forground windows and balooon tip is hidden and disabled in my settings. I'm a software developer and i'm pretty sure its not related to windows but my windows is 10 anyway.

reproducing steps are just to install openvpn on a windows which have multi language/direction keyboards and default system locale is not set to english (ex. Persian in my case). Its always setting keyboard to "RTL"(I think its selected locale in windows region settings) on every connect/recoonect without permission. It doesn't even care to preferred keyboard language in language preferences Also its good to mention that there is no "Persian" word in my connection script when its switching to Persian language. All script log messages are in english in my case because I always prefer English language in my application and windows locale setting is just for correctly reading of non unicode text files in apps.

its too too  too very very much annoying specially while you working.
